### PR TITLE
Adding new jupyter notebook (binder doesn't work yet)

### PR DESCRIPTION
**Pull request by byrolew**

### CODE REVIEW

**Comment by agosiewska** [comment]
Thanks @byrolew 
Travis build is failing due to the undocumented datasets ‘dragons’ and ‘dragons_test’.

An example, how to do it is here:
https://github.com/MI2DataLab/auditor/blob/master/R/auditorData.R
It would be great if you could add descriptions of columns.

**Comment by byrolew** [comment]
Should be okay now, the binder will be added after merge, because I want to build it on master not my own branch.

**Comment by byrolew** [comment]
Temporary link to binder built on my branch:
https://hub.mybinder.org/user/mi2datalab-auditor-5cx8bjgz/notebooks/jupyter-notebooks/auditor_dragons_demo.ipynb

**Comment by agosiewska** [comment]
Binder on your branch is not working for me, but I'm merging to allow you building it on master :)
image

**Pull request merged**
